Numpy 

In [1]:
import numpy as np

In [2]:
#1-D array
a=np.array([1,2,3])
a


array([1, 2, 3])

In [3]:
#2-D array
b=np.array([
    [1.0,1.0],
    [1.0,1.0]
    
])
b

array([[1., 1.],
       [1., 1.]])

In [4]:
c=np.array([1,2,3],dtype="int16")

In [5]:
print(a)
print(b)
print(c)

[1 2 3]
[[1. 1.]
 [1. 1.]]
[1 2 3]


In [6]:
print(a.dtype)
print(b.dtype)
print(c.dtype)

int32
float64
int16


In [7]:
print(a.ndim)
print(b.ndim)
print(c.ndim)

1
2
1


In [8]:
print(a.shape)
print(b.shape)
print(c.shape)

(3,)
(2, 2)
(3,)


In [9]:
print(a.itemsize)
print(b.itemsize)
print(c.itemsize)

4
8
2


In [10]:
print(a.size * a.itemsize)

12


In [11]:
print(a.nbytes)

12


In [12]:
arr=[range(1,5),range(5,9)]
np.array(arr)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
a=np.array(np.arange(24))
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [14]:
np.array(np.arange(24)).reshape(3,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [15]:
np.array(np.arange(24)).reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [16]:
c=np.array(np.arange(24)).reshape(2,3,4) *10 +3
c

array([[[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [17]:
a=np.array([1,2,3])
c=np.array([1,2,3],dtype="int16")
np.append(a,c, axis=0)

array([1, 2, 3, 1, 2, 3])

In [18]:
a=np.array(np.arange(24)).reshape(2,3,4)
c=np.array(np.arange(24)).reshape(2,3,4) *10 +3
np.append(a,c, axis=1)

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [19]:
a=np.array(np.arange(24)).reshape(2,3,4)
c=np.array(np.arange(24)).reshape(2,3,4) *10 +3
np.append(a,c, axis=0)

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]],

       [[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [20]:
a=np.array(np.arange(24)).reshape(2,3,4)
c=np.array(np.arange(24)).reshape(2,3,4) *10 +3
np.append(a,c, axis=2)

array([[[  0,   1,   2,   3,   3,  13,  23,  33],
        [  4,   5,   6,   7,  43,  53,  63,  73],
        [  8,   9,  10,  11,  83,  93, 103, 113]],

       [[ 12,  13,  14,  15, 123, 133, 143, 153],
        [ 16,  17,  18,  19, 163, 173, 183, 193],
        [ 20,  21,  22,  23, 203, 213, 223, 233]]])

In [22]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [23]:
a[1,5]

13

In [24]:
a[1][5]

13

In [25]:
a[1][-2]

13

In [27]:
a[0:1,0:5]

array([[1, 2, 3, 4, 5]])

In [28]:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [29]:
a[:,2]


array([ 3, 10])

# Pandas

Series: 1-D array, sequence of elements,associated array of labels(index)
    

In [31]:
import numpy as np
import pandas as pd

In [32]:
o1=pd.Series([4,7,-5,3])
o1

0    4
1    7
2   -5
3    3
dtype: int64

In [33]:
o1.values

array([ 4,  7, -5,  3], dtype=int64)

In [34]:
o2=pd.Series([4,7,-5,3], index=['d','k','c','a'])
o2

d    4
k    7
c   -5
a    3
dtype: int64

In [35]:
o2['d']

4

In [38]:
o3= pd.Series([4,7,-5,3])
o3

0    4
1    7
2   -5
3    3
dtype: int64

In [39]:
o4=pd.Series([1,"Gaurav",3.5,"Aviral"])
o4

0         1
1    Gaurav
2       3.5
3    Aviral
dtype: object

In [ ]:
DataFrame:

In [47]:
data={"name":["Bill","Tom","Tim","John","Alex","Vanessa","Kate"],      
      "score":[90,80,85,75,95,60,65],      
      "sport":["Wrestling","Football","Skiing","Swimming","Tennis",
               "Karete","Surfing"],      
      "sex":["M","M","M","M","F","F","F"]}


In [48]:
df=pd.DataFrame(data)
df

name  score      sport sex
0     Bill     90  Wrestling   M
1      Tom     80   Football   M
2      Tim     85     Skiing   M
3     John     75   Swimming   M
4     Alex     95     Tennis   F
5  Vanessa     60     Karete   F
6     Kate     65    Surfing   F

In [50]:
df.head(2)

name  score      sport sex
0  Bill     90  Wrestling   M
1   Tom     80   Football   M

In [51]:
df.tail(2)

name  score    sport sex
5  Vanessa     60   Karete   F
6     Kate     65  Surfing   F

In [56]:
df=pd.DataFrame(data,columns=["name", "sport","sex","age"])

In [57]:
df

name      sport sex  age
0     Bill  Wrestling   M  NaN
1      Tom   Football   M  NaN
2      Tim     Skiing   M  NaN
3     John   Swimming   M  NaN
4     Alex     Tennis   F  NaN
5  Vanessa     Karete   F  NaN
6     Kate    Surfing   F  NaN

In [58]:
df["sport"]

0    Wrestling
1     Football
2       Skiing
3     Swimming
4       Tennis
5       Karete
6      Surfing
Name: sport, dtype: object

In [59]:
df1=["sport","name"]
df[df1]

sport     name
0  Wrestling     Bill
1   Football      Tom
2     Skiing      Tim
3   Swimming     John
4     Tennis     Alex
5     Karete  Vanessa
6    Surfing     Kate

In [60]:
df["age"]=20

In [61]:
df

name      sport sex  age
0     Bill  Wrestling   M   20
1      Tom   Football   M   20
2      Tim     Skiing   M   20
3     John   Swimming   M   20
4     Alex     Tennis   F   20
5  Vanessa     Karete   F   20
6     Kate    Surfing   F   20